import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "hooks/index": "src/hooks/index.ts",
    "query/filters": "src/query/filters.ts",
    "query/queryBuilder": "src/query/queryBuilder.ts",
    "query/pagination": "src/query/pagination.ts",
    "auth/authStore": "src/auth/authStore.ts",
    "auth/authGate": "src/auth/authGate.ts",
    "realtime/realtimeManager": "src/realtime/realtimeManager.ts",
    "persistence/persistenceAdapter": "src/persistence/persistenceAdapter.ts",
    "rpc/rpcAction": "src/rpc/rpcAction.ts",
    "functions/edgeFunctions": "src/functions/edgeFunctions.ts",
    "storage/storageActions": "src/storage/storageActions.ts",
    "sync/crossTabSync": "src/sync/crossTabSync.ts",
    "sync/incrementalSync": "src/sync/incrementalSync.ts",
    "cache/cacheTtl": "src/cache/cacheTtl.ts",
    "server/prefetch": "src/server/prefetch.ts",
    "lifecycle/appLifecycle": "src/lifecycle/appLifecycle.ts",
    "sync/backgroundSync": "src/sync/backgroundSync.ts",
    "sync/selectiveSync": "src/sync/selectiveSync.ts",
    "sync/multiDeviceSync": "src/sync/multiDeviceSync.ts",
    "sync/syncMetrics": "src/sync/syncMetrics.ts",
    "persistence/encryptedAdapter": "src/persistence/encryptedAdapter.ts",
    "persistence/storageQuota": "src/persistence/storageQuota.ts",
    "persistence/schemaVersion": "src/persistence/schemaVersion.ts",
    "mutation/conflictAudit": "src/mutation/conflictAudit.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: [
    "zustand",
    "zustand/middleware",
    "zustand/shallow",
    "zustand/react/shallow",
    "zustand/vanilla",
    "@supabase/supabase-js",
    "react",
    "immer",
  ],
})
